---
language: ruby
rvm:
- 1.9.2
- 1.9.3
- 1.8.7
script: bundle exec rake spec
after_success:
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
- .forge-releng/publish
env:
  global:
  - PUBLISHER_LOGIN=garethr
  - secure: ! 'LxoSw6XeoEUxspruNjLfdqmYYWCXMFNB41ZZYUhcZBDREfeETkkynkX7uuUm
      t/KBTsaTyxGMeW1UcAJsHhufs6sTc8zi0O7QUXC/jmO0pDE19HzdHz18bCq1
      QEgZ+h8ikZ4snn7AKIQNpUA/UUIgdOAq+HM17y3q70FMlebDBqE='
  matrix:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=3.0.1
  - PUPPET_VERSION=3.1.0
