name        'garethr-wackopicko'
version     '0.0.1'
source      'git://github.com/garethr/garethr-wackopicko.git'
author      'Gareth Rushgrove'
summary     'Module for installing wackopicko'
description 'Wackopicko is an insecure PHP web application used for penetration testing'
license     'Apache License, Version 2.0'

dependency  'puppetlabs/stdlib', '>=3.2.0'
dependency  'puppetlabs/git', '>=0.0.2'
dependency  'puppetlabs/vcsrepo', '>=0.1.1'
dependency  'puppetlabs/mysql', '>=0.6.1'
dependency  'puppetlabs/apache', '>=0.6.0'
dependency  'saz/php', '>=1.0.4'
